### PR TITLE
Sleaze res at bar

### PR DESCRIPTION
**Pull request by Ignose**

### CODE REVIEW

**Comment by fewyn** [comment]
I'd recommend adding a few more skills to the sleaze res line. Specifically "Scarysauce, Astral Shell, Elemental Saucesphere".

Also not sure if there is a better place but also needed to update my Recover to be 0.95 instead of 0.75 as I was getting beaten up occasionally.

**Comment by Rinn** [comment]
i don't know if mafia will automatically do it, but it would be straightforward if the player has a [velour viscometer](https://kol.coldfront.net/thekolwiki/index.php/Velour_viscometer) to equip it and cast scarysauce for scariersauce which is +6 and stacks with scarysauce.

**Comment by Rinn** [comment]
please fix that lint error and this is good to go, i can add scariersauce later

**Comment by MrFizzyBubbs** [comment]
Is the yarn lock change necessary?

**Comment by Ignose** [comment]
No. I did a yarn install and it updated automatically.

**Pull request merged**
