### PR TITLE
feat: pickpocket except against multidrop monsters

### PR DESCRIPTION
**Pull request by midgleyc**
You can pickpocket the common drops, so try to do that. However, don't try against the mudlark or engineer: these drop 1-3 of the flotsam or machine parts normally, and if you pickpocket you always get one.

Don't condition on being able to pickpocket because if you submit a macro where you try to pickpocket but can't, you just don't. Efficient! And also I'm not certain how to check for this without enumerating all the possible cases.

Value mime army infiltration glove at 2k: it's about 5% of a common drop, and the farmable ones are 30k-50k. Might get a better valuation later but I think this is good enough for now.

### CODE REVIEW

**Comment by MrFizzyBubbs** [comment]
Would it be worth using the mall price or the cheapest/average common drop for the valuation rather than hard coding?

**Comment by midgleyc** [comment]
Definitely, but pulling out the common drops given a location is nontrivial (unless I just hardcode them I guess).

**Comment by MrFizzyBubbs** [comment]
The zone monsters are hardcoded for the `orb` arg so that seems reasonable to me.

**Comment by midgleyc** [comment]
righto, updated (but not tested)

**Pull request merged**
